# Generated by Django 3.0.1 on 2020-03-03 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='form_field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template', models.CharField(max_length=190)),
                ('attribute', models.CharField(max_length=200)),
                ('question', models.CharField(max_length=400, null=True)),
                ('required', models.BooleanField(null=True)),
                ('options', models.TextField(null=True)),
                ('filled', models.BooleanField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('form_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.forms')),
            ],
        ),
        migrations.CreateModel(
            name='modify_form_responses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_code', models.CharField(max_length=190)),
                ('respondent_ip', models.GenericIPAddressField()),
                ('respondent_user_agent', models.CharField(max_length=190)),
                ('form_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.forms')),
            ],
        ),
        migrations.CreateModel(
            name='form_response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('field_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.form_field')),
                ('form_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.forms')),
            ],
        ),
    ]
