# Generated by Django 3.0.1 on 2020-03-07 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_form_field_form_response_modify_form_responses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forms',
            name='code',
            field=models.SlugField(max_length=250, unique=True),
        ),
    ]
